# ~/.config/kitty/themes/homage-white.conf

# Background & Foreground
background             #fafafa
foreground             #383a42

# Cursor
cursor                 #383a42
cursor_text_color      #fafafa

# Selection
selection_background   #c6c7c7
selection_foreground   #383a42

# URL color
url_color              #014980

# 16 terminal colors
# Black
color0                 #1b2229
color8                 #9ca0a4
# Red
color1                 #e45649
color9                 #e45649
# Green
color2                 #556b2f
color10                #4db5bd
# Yellow
color3                 #986801
color11                #8a3b3c
# Blue
color4                 #014980
color12                #030f64
# Magenta
color5                 #a626a4
color13                #b751b6
# Cyan
color6                 #0184bc
color14                #005478
# White
color7                 #c6c7c7
color15                #fafafa
